"""Output generation: RSS 2.0 XML, catalogue JSON, and index HTML."""

import json
import logging
from datetime import UTC, datetime
from email.utils import format_datetime

from jinja2 import Environment, PackageLoader
from lxml import etree

from australianewsrss.models import NormalisedArticle, PublisherConfig
from australianewsrss.state import FeedRegistry

logger = logging.getLogger(__name__)

# RSS 2.0 namespace URIs
_ATOM_NS = "http://www.w3.org/2005/Atom"
_MEDIA_NS = "http://search.yahoo.com/mrss/"
_DC_NS = "http://purl.org/dc/elements/1.1/"
_CONTENT_NS = "http://purl.org/rss/1.0/modules/content/"

_NSMAP: dict[str, str] = {
    "atom": _ATOM_NS,
    "media": _MEDIA_NS,
    "dc": _DC_NS,
    "content": _CONTENT_NS,
}


def generate_rss(
    articles: list[NormalisedArticle],
    publisher: PublisherConfig,
    self_url: str,
) -> str:
    """Build an RSS 2.0 XML document from normalised articles.

    Returns the complete XML as a string with XML declaration.
    """
    rss = etree.Element("rss", version="2.0", nsmap=_NSMAP)
    channel = etree.SubElement(rss, "channel")

    # Channel-level elements
    _add_text(channel, "title", f"{publisher.name} \u2014 All Feeds")
    _add_text(channel, "link", publisher.base_url)
    _add_text(
        channel,
        "description",
        f"Aggregated RSS feed from {publisher.name}. Generated by AustraliaNewsRSS.",
    )
    _add_text(channel, "language", "en-AU")
    _add_text(channel, "generator", "AustraliaNewsRSS/0.1")
    _add_text(
        channel,
        "copyright",
        f"Content copyright {publisher.name}. Feed aggregation by AustraliaNewsRSS.",
    )

    # atom:link self-reference
    etree.SubElement(
        channel,
        f"{{{_ATOM_NS}}}link",
        href=self_url,
        rel="self",
        type="application/rss+xml",
    )

    # Items
    for article in articles:
        _build_item(channel, article)

    logger.debug(
        "Generated RSS with %d items for %s",
        len(articles),
        publisher.slug,
    )

    xml_bytes: bytes = etree.tostring(
        rss,
        encoding="UTF-8",
        xml_declaration=True,
        pretty_print=True,
    )
    return xml_bytes.decode("utf-8")


def _add_text(parent: etree._Element, tag: str, text: str) -> None:
    """Add a simple text child element."""
    el = etree.SubElement(parent, tag)
    el.text = text


def _build_item(
    channel: etree._Element,
    article: NormalisedArticle,
) -> None:
    """Build an <item> element from a NormalisedArticle."""
    item = etree.SubElement(channel, "item")

    _add_text(item, "title", article.title)
    _add_text(item, "link", article.url)

    guid = etree.SubElement(item, "guid", isPermaLink="true")
    guid.text = article.guid

    if article.published is not None:
        _add_text(item, "pubDate", format_datetime(article.published))

    # Description with optional image prepended as CDATA
    desc_content = ""
    if article.image_url:
        desc_content = (
            f'<img class="webfeedsFeaturedVisual" src="{article.image_url}" />'
        )
    desc_content += article.description

    desc_el = etree.SubElement(item, "description")
    desc_el.text = desc_content

    # dc:creator
    if article.author:
        _add_text(item, f"{{{_DC_NS}}}creator", article.author)

    # Category elements
    for cat in article.categories:
        _add_text(item, "category", cat)

    # Image triple (only when image_url present)
    if article.image_url:
        etree.SubElement(
            item,
            f"{{{_MEDIA_NS}}}content",
            url=article.image_url,
            type="image/jpeg",
            medium="image",
        )
        etree.SubElement(
            item,
            "enclosure",
            url=article.image_url,
            type="image/jpeg",
            length="0",
        )


# ---------------------------------------------------------------------------
# Catalogue JSON
# ---------------------------------------------------------------------------


def generate_catalogue(registry: FeedRegistry) -> str:
    """Produce a JSON catalogue of all discovered feeds.

    Returns a JSON string with ``generated_at`` timestamp and a ``feeds``
    array sorted by (publisher, url).  All feeds are included regardless
    of status so that dead/stale feeds remain visible.
    """
    feeds = registry.get_feeds()
    sorted_feeds = sorted(feeds, key=lambda f: (f.publisher, f.url))
    catalogue = {
        "generated_at": datetime.now(UTC).isoformat(),
        "feeds": [
            {
                "publisher": f.publisher,
                "title": f.title,
                "feed_id": f.feed_id,
                "category_hint": f.category_hint,
                "url": f.url,
                "status": f.status,
                "metadata": {
                    "title": f.metadata.title,
                    "description": f.metadata.description,
                    "link": f.metadata.link,
                    "language": f.metadata.language,
                    "categories": list(f.metadata.categories),
                },
                "first_seen": (f.first_seen.isoformat() if f.first_seen else None),
                "last_seen": (f.last_seen.isoformat() if f.last_seen else None),
                "last_checked": (
                    f.last_checked.isoformat() if f.last_checked else None
                ),
            }
            for f in sorted_feeds
        ],
    }
    return json.dumps(catalogue, indent=2, sort_keys=True)


# ---------------------------------------------------------------------------
# Index HTML
# ---------------------------------------------------------------------------


def generate_index(
    registry: FeedRegistry,
    output_feeds: dict[str, str],
) -> str:
    """Render an HTML index page with per-publisher feed listings.

    *output_feeds* maps publisher slug to generated feed URL
    (e.g. ``{"abc": "feed/abc.xml"}``).
    """
    feeds = registry.get_feeds()
    sorted_feeds = sorted(feeds, key=lambda f: (f.publisher, f.url))

    publishers: dict[str, list[object]] = {}
    for feed in sorted_feeds:
        publishers.setdefault(feed.publisher, []).append(feed)

    env = Environment(
        loader=PackageLoader("australianewsrss", "templates"),
        autoescape=True,
    )
    template = env.get_template("index.html.j2")
    return template.render(
        publishers=publishers,
        output_feeds=output_feeds,
        generated_at=datetime.now(UTC).isoformat(),
    )
